---
- hosts: localhost
  vars:
    
  tasks:
  - name: Verify that required variables are defined
    assert:
      that:
        - account_id is defined
        - profile is defined
        #- aws_region is defined
      msg: Verify that required variables account_name, iam_role, and aws_region areundefined
   # Lists all s3 buckets
  - name: list buckets
    community.aws.aws_s3_bucket_info:
      profile: "{{ profile }}"
    register: result

  - name: List buckets
    ansible.builtin.debug:
      msg: "{{ result['buckets'] }}"